import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
assert.match(css,/html,body\{[^}]*touch-action:pan-y/);
assert.match(css,/#v\{[^}]*touch-action:pan-y/);
assert.match(css,/\.value-slider\{[^}]*height:52px/);
assert.match(css,/\.value-slider \.range\{[^}]*opacity:1/);
assert.match(css,/\.value-slider \.range\{[^}]*pointer-events:auto/);
assert.doesNotMatch(app,/const PX_PER_STEP=36/);
assert.doesNotMatch(app,/const bindRuler=wrap=>/);
assert.match(app,/const waitForSWInstall=/);
assert.match(app,/await activateSW\(waiting\)/);
console.log('gesture safety ok');
