import fs from 'node:fs';
import assert from 'node:assert/strict';
const a=fs.readFileSync('app.js','utf8'),h=fs.readFileSync('index.html','utf8'),l=fs.readFileSync('lift-local.html','utf8'),s=fs.readFileSync('styles.css','utf8');
assert.match(a,/const BUILD_VERSION='[^']+'/);
assert.match(a,/const installGuideDevice=/);
assert.match(a,/installGuide:\(\)=>installGuideOpen\(\)/);
assert.match(a,/installGuideSeen/);
assert.match(a,/Open as Web App/);
assert.match(a,/display-mode: standalone/);
assert.match(a,/iPad\|iPhone\|iPod/);
assert.match(a,/Android/);
assert(a.includes('iPhone/iPad: use Safari for the web-app install. Chrome is not supported for this install flow.'));
assert.match(h,/offline web-app installation guide/);
assert.match(l,/offline web-app installation guide/);
assert.match(h,/Safari for the web-app install/);
assert.match(l,/Safari for the web-app install/);
assert.match(s,/offline web-app installation guide/);
assert.match(s,/\.ig-warning/);
console.log('install-guide regression: PASS');
