import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../ranking-engine.js',import.meta.url),'utf8');
const ctx={console};vm.runInNewContext(src,ctx);
const E=ctx.LiftRankingEngine;
const R=JSON.parse(fs.readFileSync(new URL('../ranks-config.json',import.meta.url),'utf8'));
const C=R.ranking;
const set=(kg,reps,t='')=>({kg,reps,t});
const score=(name,kg,reps,bw,sex='M',height=178,age=25)=>{
 const e=E.estimate1RM(set(kg,reps),R.exerciseMeta[name],bw,C);
 return E.adjustedScore(e,bw,sex,height,age,R.exerciseMeta[name],C);
};
assert.equal(E.estimate1RM(set(100,1),R.exerciseMeta['Bench Press'],75,C),100);
assert.equal(E.estimate1RM(set(100,13),R.exerciseMeta['Bench Press'],75,C),0);
assert.ok(R.t['Bench Press'][0][45] < R.t['Leg Press'][0][45]);
assert.notDeepEqual(R.t['Bench Press'][0],R.t['Bench Press'][1]);
assert.ok(score('Bench Press',120,1,75,'M') > score('Bench Press',120,1,75,'F'));
assert.ok(score('Bench Press',100,1,60,'M') > score('Bench Press',100,1,120,'M'));
assert.ok(score('Bench Press',100,1,75,'M',178,50) > score('Bench Press',100,1,75,'M',178,25));
assert.ok(score('Bench Press',100,1,75,'M',190,25) < score('Bench Press',100,1,75,'M',165,25),'height correction must penalize taller athletes');
assert.equal(E.effectiveLoad(set(10,1),R.exerciseMeta['Dumbbell Bench Press'],75),20);
assert.equal(E.effectiveLoad(set(20,1),R.exerciseMeta['Pull-Up'],75),95);
assert.equal(E.effectiveLoad(set(20,1),R.exerciseMeta['Assisted Pull-Up Machine'],75),55);
assert.ok(E.percentileScore(score('Bench Press',100,1,75,'M'),R.t['Bench Press'][0],C)>E.percentileScore(score('Leg Press',100,1,75,'M'),R.t['Leg Press'][0],C),'exercise-specific standards must separate bench from leg press');
assert.ok(score('Bench Press',100,1,75,'M',178,25)>0);
assert.ok(score('Bench Press',100,1,75,'M',190,25)<score('Bench Press',100,1,75,'M',165,25),'height/ROM correction must be active');
assert.ok(score('Bench Press',100,1,75,'M',178,50)>score('Bench Press',100,1,75,'M',178,25),'age correction must be active');
assert.equal(E.effectiveLoad(set(20,1),R.exerciseMeta['Dumbbell Bench Press'],75),40,'bilateral dumbbell load uses both hands');
assert.equal(E.effectiveLoad(set(20,1),{...R.exerciseMeta['Dumbbell Bench Press'],unilateral:true},75),20,'unilateral load stays per side');
assert.equal(E.estimate1RM(set(0,1),R.exerciseMeta['Bench Press'],68,C),0);
assert.equal(E.rankIndex(score('Bench Press',0,1,68,'M'),R.t['Bench Press'][0]),-1,'zero load must never rank');
assert.ok(score('Bench Press',100,1,75,'M',178,17)>score('Bench Press',100,1,75,'M',178,20),'age correction must distinguish 17 from 20');
assert.equal(E.effectiveLoad(set(3.875,1),R.exerciseMeta['Dumbbell Bicep Curl'],75),7.75);
assert.ok(E.rankIndex(7.75,R.t['Dumbbell Bicep Curl'][0])>=0,'DB threshold units must match effective-load units');
console.log('ranking engine v8 regression tests passed');
