import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
const anatomy=fs.readFileSync('anatomy-map.css','utf8');
const colorCss=css+anatomy;
const html=fs.readFileSync('index.html','utf8');
const palette=['#8a5a44','#b87333','#c0c0c0','#d4af37','#9ed8ff','#50c878','#0f52ba','#e0115f','#b9f2ff','#238cff'];
assert.equal((app.match(/const RANK_FAMILY_COLORS=\[/)||[]).length,1);
for (const c of palette) assert.ok(app.includes(c),`missing rank family color ${c}`);
assert.ok(app.includes("'+rankTextColor(i)+'"));
assert.ok(app.includes("--ms:") && app.includes("const stroke=i>=0?rankShade(i,-.18):lockedStroke(id)"));
assert.match(css,/\.rank-icon svg path\{fill:var\(--c\)!important/);
assert.match(css,/\.badge\{color:var\(--ct,#fff\)!important;background:var\(--c\)!important/);
assert.match(colorCss,/\.muscle-zone-group\.unlocked path[\s\S]*fill:var\(--mc/);
assert.match(colorCss,/stroke:var\(--ms,var\(--mc/);
assert.match(html,/BUILD_VERSION='5\.5\.89'/);
assert.match(html,/authoritative rank-color layer/);
assert.match(html,/authoritative 2D anatomy color layer/);
console.log('rank/anatomy color regression: ok');
