import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const app=fs.readFileSync('app.js','utf8');
const exerciseData=JSON.parse(fs.readFileSync('exercises.json','utf8'));const rankData=JSON.parse(fs.readFileSync('ranks-config.json','utf8'));assert(exerciseData.ex.length>=300,'exercise library should contain at least 300 entries');const exerciseRows=exerciseData.ex.map(x=>x.split('|'));assert(exerciseRows.every(x=>x.length>=4&&x[0]&&x[3]),'every catalogue exercise should have name, split, load type and picker category');for(const n of ['Cable Lateral Raise','Dumbbell Bicep Curl','Machine Biceps Curl','Incline Dumbbell Curl','Single-Arm Cable Curl','Rope Triceps Pushdown','Bayesian Cable Curl'])assert(exerciseRows.some(x=>x[0]===n),`missing common exercise ${n}`);for(const n of ['Cable Lateral Raise','Dumbbell Bicep Curl','Rope Triceps Pushdown'])assert(rankData.alias[n],`missing benchmark alias for ${n}`);

execFileSync(process.execPath,['--check','app.js']);
for(const n of ['index.html','lift-local.html']){const h=fs.readFileSync(n,'utf8'),m=h.match(/<script[^>]*>([\s\S]*?)<\/script>/);assert(m,`${n} missing inline app`);execFileSync(process.execPath,['--check'],{input:m[1]});assert(!h.includes('user-scalable=no'));assert(h.includes('.row>.toggle{width:auto;flex:0 0 auto;min-width:88px'));assert(h.includes('.add{align-items:center}'));assert(h.includes('.exercise-library-panel{'));assert(h.includes('.exercise-option{'));assert(h.includes('＋ Browse exercise library'));assert(!h.includes('.toggle{width:100%'));}
const idx=fs.readFileSync('index.html','utf8').match(/<script[^>]*>([\s\S]*?)<\/script>/)[1];const loc=fs.readFileSync('lift-local.html','utf8').match(/<script[^>]*>([\s\S]*?)<\/script>/)[1];assert.equal(idx,loc);
assert(app.includes("if(t.id==='age'||t.id==='heightCm'){S.set[t.id==='age'?'age':'heightCm']=t.value;S.savedAt=Date.now();localSave()}"),'profile drafts must persist while typing');
for(const marker of ['exercise-library-panel','exercisePickerResults','exercisePickerCategory','data-a=\"pickx\"','data-a=\"addcustom\"','id=\"ex-search\"','EX[n]={g,t,c:c||g}','data-a=\"openx\"'])assert(app.includes(marker),`missing exercise picker feature ${marker}`);const embedded=app.slice(app.indexOf('const EMBED_X=')+'const EMBED_X='.length,app.indexOf(',EMBED_R='));assert.deepEqual(JSON.parse(embedded),exerciseData,'offline embedded exercise catalogue must match exercises.json');const embeddedRanks=app.slice(app.indexOf('EMBED_R=')+'EMBED_R='.length,app.indexOf(';',app.indexOf('EMBED_R=')));assert.deepEqual(JSON.parse(embeddedRanks),rankData,'offline embedded rank aliases must match ranks-config.json');
for(const marker of ['qolShowProgress','qolRestStart','qolPlatePlan','qolAgeFactor','heightFactor','S.editingId','savedAt','navigator.wakeLock','MUSCLE_LIFTS','muscleStates','rearDelts','tutorialSteps','theme-choices','body-spin','credits-card','retryRender','Could not load','skinFace','skinBackFace','aria-label=\"Front body muscle map\"'])assert(app.includes(marker),`missing ${marker}`);
const model=fs.readFileSync('muscle3d.js','utf8');execFileSync(process.execPath,['--check','muscle3d.js']);
for(const marker of ['getContext(','DEPTH_TEST','pointerdown','pointermove','data-muscle-turn','body-stage'])assert(model.includes(marker),`3D renderer missing ${marker}`);
for(const n of ['index.html','lift-local.html']){const h=fs.readFileSync(n,'utf8'),scripts=[...h.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);assert.equal(scripts.length,n==='lift-local.html'?6:5,`${n} must embed app, local Three.js loaders, and renderer`);assert.equal(scripts[0],app,`${n} app is stale`);assert.equal(scripts[scripts.length-1],model,`${n} renderer is stale`);assert(scripts[1]===''&&scripts[2]===''&&scripts[3]==='',`${n} external scripts must not contain inline code`);if(n==='lift-local.html'){const dm=h.match(/<script id="lift-anatomy-data">window.LIFT_ANATOMY_GZ_BASE64='([^']+)';<\/script>/);assert(dm,'standalone HTML must embed the anatomy data');assert.equal(Buffer.from(dm[1],'base64').compare(fs.readFileSync('body.glb.gz')),0,'embedded anatomy must match cached model asset')}assert(h.includes('lift-icon-180-v2.png'));assert(h.includes('lift-icon-192-v2.png'));assert(h.includes('lift-icon-v2.svg'));assert(h.includes('manifest.webmanifest'));assert(h.includes('apple-mobile-web-app-capable\" content=\"yes'));assert(h.includes('apple-mobile-web-app-title\" content=\"Lift'));assert(h.includes('viewport-fit=cover'));}
for(const [n,w] of [['lift-icon-192-v2.png',192],['lift-icon-512-v2.png',512],['lift-icon-180-v2.png',180]]){const b=fs.readFileSync(n);assert.equal(b.subarray(0,8).toString('hex'),'89504e470d0a1a0a',`${n} must be a PNG`);assert.equal(b.readUInt32BE(16),w,`${n} width`);assert.equal(b.readUInt32BE(20),w,`${n} height`)}
const sw=fs.readFileSync('sw.js','utf8');for(const n of ['lift-icon-180-v2.png','lift-icon-192-v2.png','lift-icon-512-v2.png','lift-icon-v2.svg','manifest.webmanifest'])assert(sw.includes(n));
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));assert.equal(manifest.display,'standalone');assert.equal(manifest.start_url,'./index.html?source=homescreen-v2');assert(manifest.icons.some(i=>i.src==='./lift-icon-192-v2.png'));assert(manifest.icons.some(i=>i.src==='./lift-icon-512-v2.png'));
const fsPath=fs.existsSync('body.glb.gz');assert(fsPath,'compressed segmented anatomy GLB missing');const {gunzipSync}=await import('node:zlib');const glb=gunzipSync(fs.readFileSync('body.glb.gz'));assert.equal(glb.subarray(0,4).toString(),'glTF');assert.equal(glb.readUInt32LE(4),2);assert.equal(glb.readUInt32LE(8),glb.length);for(const n of ['three.min.js','GLTFLoader.js','DRACOLoader.js','draco/draco_decoder.js','draco/draco_wasm_wrapper.js','draco/draco_decoder.wasm','THREE-LICENSE.txt','ANATOMY-ATTRIBUTION.md'])assert(fs.statSync(n).size>100,`${n} missing or too small`);
const classifyExpr=model.match(/function classifyMuscle\(name\)\{([\s\S]*?)\}\nfunction initAnatomy/)[1];const classify=Function('name',classifyExpr);for(const [n,g] of [['Clavicular head of pectoralis major muscle','chest'],['Clavicular part of deltoid muscle','frontDelts'],['Acromial part of deltoid muscle','sideDelts'],['Scapular spinal part of deltoid muscle','rearDelts'],['Long head of biceps brachii','biceps'],['Lateral head of triceps brachii','triceps'],['Rectus abdominis muscle','abs'],['Latissimus dorsi muscle','lats'],['Gluteus maximus muscle','glutes'],['Vastus lateralis muscle','quads'],['Semitendinosus muscle','hamstrings'],['Gastrocnemius muscle','calves'],['Pectoralis minor muscle',null],['Parietal bone',null],['Skin',null],['Rectus abdominis muscle','abs'],['External abdominal oblique muscle','abs'],['Gluteus maximus muscle','glutes'],['Gluteus minimus muscle',null],['Vastus intermedius muscle',null],['Soleus muscle',null]])assert.equal(classify(n),g,`${n} should map to ${g}`);const anatomy=JSON.parse((await import('node:zlib')).gunzipSync(fs.readFileSync('body.glb.gz')).subarray(20,20+(await import('node:zlib')).gunzipSync(fs.readFileSync('body.glb.gz')).readUInt32LE(12)).toString());const meshGroups=new Set(anatomy.nodes.filter(n=>n.mesh!==undefined).map(n=>classify(n.name)));for(const g of ['chest','frontDelts','sideDelts','rearDelts','biceps','triceps','lats','upperBack','abs','glutes','quads','hamstrings','calves'])assert(meshGroups.has(g),`anatomy model missing visible rank group ${g}`);assert(meshGroups.has(null),'unmapped bone/non-target meshes must be excluded by the allowlist');assert(model.includes('userData.liftMuscleName=o.name||name'));assert(model.includes("userData.liftRankClass=\'muscle-\'+rankGroup"));
assert(model.includes("fetch('./body.glb.gz')"));assert(model.includes('LIFT_ANATOMY_GZ_BASE64'));assert(model.includes("location.protocol==='file:'?'js':'wasm'"));assert(model.includes('EdgesGeometry(o.geometry,38)'));assert(model.includes('if(rankGroup){const eg=new THREE.EdgesGeometry'));assert(model.includes('depthWrite:true'));assert(model.includes('alpha:.20'));assert(model.includes('edgeAlpha:.24'));assert(model.includes('alpha:.78'));assert(model.includes('edgeAlpha:.62'));assert(model.includes('if(!rankGroup){o.visible=false;return}'));assert(model.includes('childList:true'));assert(model.includes('THREE.DoubleSide'));assert(model.includes('userData.liftGroup=rankGroup'));assert(model.includes('THREE.DRACOLoader'));assert(model.includes('new THREE.HemisphereLight'));assert(model.includes('data-muscle-turn'));
for(const n of ['index.html','lift-local.html']){const h=fs.readFileSync(n,'utf8');for(const x of ['three.min.js','GLTFLoader.js','DRACOLoader.js','body.glb.gz','Anatomy: hpfrei / Z-Anatomy'])assert(h.includes(x)||fs.readFileSync('app.js','utf8').includes(x),`${n} missing ${x}`)}
for(const n of ['lift-icon-v2.svg','lift-icon-180-v2.png','lift-icon-192-v2.png','lift-icon-512-v2.png','body.glb.gz','three.min.js','GLTFLoader.js','DRACOLoader.js','draco/draco_decoder.js','draco/draco_wasm_wrapper.js','draco/draco_decoder.wasm','ANATOMY-ATTRIBUTION.md'])assert(fs.readFileSync('sw.js','utf8').includes(n),`service worker missing ${n}`);
const ageExpr=app.match(/const qolAgeFactor=([\s\S]*?);\s*const heightFactor=/)[1].replace(/;\s*$/,'');const age=Function(`return (${ageExpr})`)();assert(Math.abs(age(40)-1)<1e-9);assert(Math.abs(age(45)-.975)<1e-9);assert(Math.abs(age(70)-.85)<1e-9);assert.equal(age(45,false),1);
assert(app.includes("Math.pow(175/n,.15)"));
const plateExpr=app.match(/const qolPlatePlan=([\s\S]*?);\s*const qolRankedNames=/)[1].replace(/;\s*$/,'');const plate=Function('const num=v=>parseFloat(String(v).replace(\',\',\'.\'))||0;return ('+plateExpr+')')();const pr=plate(100,20);assert.equal(pr.side,40);assert(pr.exact);assert.deepEqual(pr.plates,[{plate:25,count:1},{plate:15,count:1}]);
console.log('smoke tests passed');
