import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
assert.match(app,/const TUTORIAL_VERSION=5;/);
assert.match(app,/tutorialSteps=/);
assert.match(app,/tutorialReady/);
assert.match(app,/tutorial-spotlight/);
assert.match(app,/Create a workout/);
assert.match(app,/Add an exercise/);
assert.match(app,/Log weight \+ reps/);
assert.match(app,/Finish the workout/);
assert.match(app,/Open History/);
assert.match(app,/Open Ranks/);
assert.match(app,/Open Get your rank/);
assert.match(app,/See the anatomy map/);
assert.match(app,/Open Profile/);
assert.match(app,/Credits/);
assert.doesNotMatch(css,/tutorial-layer[^\\n]*backdrop-filter:blur/);
assert.match(css,/tutorial-layer\{[^}]*backdrop-filter:none/);
assert.match(css,/tutorial-layer\.no-target/);
assert.match(css,/tutorial-spotlight/);
assert.match(css,/z-index:1600/);
console.log('tutorial v4 regression passed');
